### ISSUE TITLE
Abnormal shape rendering

### ISSUE THREAD

**Issue by Folas1337** [CreativeCraft/squaremap-plotsquared#1]
When plots are merged and then don't make a rectangular shape, it won't render properly as can be seen here: 
![image](https://user-images.githubusercontent.com/39222968/190849349-79905377-f155-43b0-9474-9b3763f353e9.png)

Due to the conversation at the end here and the hint for a possible solution by jpenilla, I thought I'd open an issue as I'd love to see a fix for this: https://github.com/jpenilla/squaremap-addons/issues/8#issuecomment-1204300977

**Comment by Log1x** [comment]
I tried my hand at this but failed. jpenilla's solution doesn't account for multi-polygon's which is what I'd need to make it work consistently.

I asked in the PlotSquared Discord for some advice on it and even the devs there were unsure of how I could approach it. :(

**Comment by Folas1337** [comment]
Well that sucks but maybe one day you'll get the once in a lifetime idea and then you can close this issue, unless you want to keep it clean but keep it in the back of your head, I'll leave that up to you ;)

**Comment by Folas1337** [comment]
I'm using Pl3xMap these days and don't need this anymore so I'll close the issue.
