### ISSUE TITLE
Support pl3xmap

### ISSUE THREAD

**Issue by Folas1337** [CreativeCraft/squaremap-plotsquared#2]
Any chance this plugin could also support pl3xmap soon? It's gotten a new version and is much faster than squaremap so I thought I'd ask :)
Here's the repo: https://github.com/BillyGalbreath/Pl3xMap

Not sure if you are maintaining this plugin at all anymore but I thought I'd at least ask.

**Comment by Log1x** [comment]
Yeah I'll try to put something together this week. :)

**Comment by Folas1337** [comment]
Damn you still alive and well <3 Hahahaha, glad you could make it this quickly or at least react, appreciate it very, very much!!

**Comment by Folas1337** [comment]
Hey there, any news on this? Although I have to admit that I may have to switch back to squaremap as pl3xmap still hasn't updated to 1.19.4 :(

Edit 1: Forget that last part, Pl3xmap just updated to 1.19.4, so I'm once again hoping this is going to become a reality :D

**Comment by Folas1337** [comment]
I hope I'm not too annoying by reminding you of this every now and then :(

Hope you're doing well!! :)

**Comment by Log1x** [comment]
Sorry for the delay. I should be updating our 1.19 server to 1.20 in the next month or so and I'll be back in the Minecraft scene for a little bit. Will get this added and update all of my plugins.

**Comment by Folas1337** [comment]
I should probably inform you that https://github.com/BillyGalbreath/Pl3xMap-Claims also added support for plotsquared so I am afraid you don't really have to do this anymore if you don't want to.
I'll leave it up to you but you may as well close it if it's less work for you, I don't mind either way, I'm personally going to use Pl3xMap-Claims though.

Still I appreciate all the support you've given so far! :)
